#include <stdio.h>

int main()
{
    int n_branches, n_prods;
    int units[100][10];
    int revenue[10];

    printf("Enter the number of branches: ");
    scanf("%d",&n_branches);
    printf("Enter the number of products: ");
    scanf("%d",&n_prods);

    printf("Enter the number of units of each product sold branch wise:\n");
    for(int i=0; i<n_branches; i++){
        printf("Branch no. %d:\n",i+1);
        for(int j=0; j<n_prods; j++){
            printf("Enter number of units of product no. %d: ",j+1);
            scanf("%d",&units[i][j]);
        }
    }

    printf("Enter the revenue generated by 1 unit of each product:\n");
    for(int i=0; i<n_prods; i++){
        printf("Revenue per unit of product no. %d: ",i+1);
        scanf("%d",&revenue[i]);
    }

    int total;

    for(int i=0; i<n_branches; i++){ // for accessing branch level data
        total = 0;
        for(int j=0; j<n_prods; j++){ // for accessing prod. data in branch
            total = total + units[i][j] * revenue[j]; // to update total
        }
        printf("The total revenue generated by branch %d = %d\n",i+1,total);
    }

    return 0;
}
